name: Comment
run-name: Run by @${{github.actor}}
on: pull_request
defaults:
  run:
    shell: bash
jobs:
  first:
    runs-on: windows-latest
    steps:
      - run: sleep 10 && echo "First job"
  second:
    runs-on: windows-latest
    steps:
      - run: sleep 10 && echo "Second job"
  third:
    runs-on: windows-latest
    steps:
      - run: sleep 10 && echo "Third job"
