name: Status check functions
on: push
jobs:
  skip-or-run:
    runs-on: windows-latest
    steps:
      - run: echo "${CONTEXT}"
        env:
          CONTEXT: ${{github.actor}}
        if: ${{github.actor == 'sasaki252511'}}
      - run: echo "Hello"
