name: GITHUB_OUTPUT
run-name: Run by @${{github.actor}}
on: push
jobs:
  share:
    runs-on: windows-latest
    steps:
      - name: github output
        id: source
        run: echo "resul=Hello">>"${GITHUB_OUTPUT}"
      - env:
        RESULT: ${{steps.source.outputs.result}}
        run: echo "${RESULT}"
